apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f kompose.yaml convert --volumes hostPath
    kompose.service.type: nodeport
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kingshard
  name: kingshard
spec:
  ports:
  - port: 9696
    protocol: TCP
  selector:
    io.kompose.service: kingshard
  type: NodePort
status:
  loadBalancer: {}
