apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f kompose.yaml convert --volumes hostPath
    kompose.service.type: nodeport
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nats
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f kompose.yaml convert --volumes hostPath
        kompose.service.type: nodeport
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nats
    spec:
      containers:
      - image: nats:latest
        imagePullPolicy: ""
        name: nats
        ports:
        - containerPort: 4222
        - containerPort: 8222
        - containerPort: 6222
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
