apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f kompose.yaml convert --volumes hostPath
    kompose.service.type: nodeport
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f kompose.yaml convert --volumes hostPath
        kompose.service.type: nodeport
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: user-service
    spec:
      containers:
      - args:
        - ./laracom-user-service
        - --server_address=:8080
        env:
        - name: DB_HOST
          value: kingshard:9696
        - name: DB_NAME
          value: laracom_user
        - name: DB_PASSWORD
          value: kingshard
        - name: DB_USER
          value: kingshard
        - name: MICRO_BROKER
          value: nats
        - name: MICRO_BROKER_ADDRESS
          value: nats:4222
        image: xueyuanjun/laracom-userservice:latest
        imagePullPolicy: Always
        name: user-service
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
