apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f kompose.yaml convert --volumes hostPath
    kompose.service.type: nodeport
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: user-db-slave-1
  name: user-db-slave-1
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    io.kompose.service: user-db-slave-1
  type: NodePort
status:
  loadBalancer: {}
