apiVersion: v1
kind: Service
metadata:
  name: micro-web
spec:
  type: LoadBalancer
  ports:
    - name: web-http
      port: 8080
      targetPort: "web-port"
      protocol: TCP
  selector:
    app: micro-web